## **Support Vector Machines (SVM)**

In [12]:
# import the librsries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# import train test split 
from sklearn.model_selection import train_test_split

# import metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,confusion_matrix, classification_report

In [10]:
df = sns.load_dataset('titanic')

# Label encode the data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])

# impute null values 
df['age'].fillna(df['age'].mean(), inplace=True)

# Selecting features and target variables 
X = df[['age', 'sex']]
y = df['survived']

# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [13]:
# Logistic Regression
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

# Evaluating the model based on metrics 
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7821229050279329
0.7536231884057971
0.7027027027027027
0.7272727272727273
0.7703989703989704
[[88 17]
 [22 52]]
              precision    recall  f1-score   support

           0       0.80      0.84      0.82       105
           1       0.75      0.70      0.73        74

    accuracy                           0.78       179
   macro avg       0.78      0.77      0.77       179
weighted avg       0.78      0.78      0.78       179



In [20]:
# SVC 
svc = SVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)

# Evaluating the model based on metrics
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.6089385474860335
0.8333333333333334
0.06756756756756757
0.12500000000000003
0.529021879021879
[[104   1]
 [ 69   5]]
              precision    recall  f1-score   support

           0       0.60      0.99      0.75       105
           1       0.83      0.07      0.13        74

    accuracy                           0.61       179
   macro avg       0.72      0.53      0.44       179
weighted avg       0.70      0.61      0.49       179



In [15]:
svc.get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [16]:
svc.support_vectors_

array([[32.,  1.],
       [ 6.,  0.],
       [36.,  1.],
       ...,
       [18.,  0.],
       [21.,  0.],
       [14.,  0.]])

In [17]:
svc.n_support_

array([268, 264])